import ToasterWrapper from "@/components/constants/Toaster";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToasterWrapper />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
